package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.ItemStockDo;
import org.example.DataObject.ItemStockDoExample;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    long countByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int deleteByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    List<ItemStockDo> selectByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    ItemStockDo selectByPrimaryKey(Integer id);

    ItemStockDo selectByItemId(Integer itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") ItemStockDo record, @Param("example") ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByExample(@Param("record") ItemStockDo record, @Param("example") ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByPrimaryKey(ItemStockDo record);
}