package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.ItemDo;
import org.example.DataObject.ItemDoExample;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    long countByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int deleteByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    List<ItemDo> selectByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    ItemDo selectByPrimaryKey(Integer id);

    List<ItemDo> listItem();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByExample(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 19 20:55:28 CST 2021
     */
    int updateByPrimaryKey(ItemDo record);

    int increaseSales(@Param("id")Integer id,@Param("amount")Integer amount);
}