package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.OrderDo;
import org.example.DataObject.OrderDoExample;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    long countByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int deleteByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int insertSelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    List<OrderDo> selectByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    OrderDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int updateByExample(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int updateByPrimaryKeySelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Apr 21 20:59:37 CST 2021
     */
    int updateByPrimaryKey(OrderDo record);
}