package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.SequenceDo;
import org.example.DataObject.SequenceDoExample;
import org.springframework.stereotype.Repository;

@Repository
public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    long countByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int deleteByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int insertSelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    List<SequenceDo> selectByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    SequenceDo selectByPrimaryKey(String name);

    SequenceDo getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int updateByExample(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Apr 21 22:43:53 CST 2021
     */
    int updateByPrimaryKey(SequenceDo record);
}