package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.StockLogDo;
import org.example.DataObject.StockLogDoExample;
import org.springframework.stereotype.Repository;

@Repository
public interface StockLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    long countByExample(StockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int deleteByExample(StockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int insert(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int insertSelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    List<StockLogDo> selectByExample(StockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    StockLogDo selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") StockLogDo record, @Param("example") StockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int updateByExample(@Param("record") StockLogDo record, @Param("example") StockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int updateByPrimaryKeySelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Mon May 17 22:12:39 CST 2021
     */
    int updateByPrimaryKey(StockLogDo record);
}