package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.DataObject.UserPwdDo;
import org.example.DataObject.UserPwdDoExample;

public interface UserPwdDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    long countByExample(UserPwdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int deleteByExample(UserPwdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int insert(UserPwdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int insertSelective(UserPwdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    List<UserPwdDo> selectByExample(UserPwdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    UserPwdDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserPwdDo record, @Param("example") UserPwdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int updateByExample(@Param("record") UserPwdDo record, @Param("example") UserPwdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int updateByPrimaryKeySelective(UserPwdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Sun Apr 11 18:21:38 CST 2021
     */
    int updateByPrimaryKey(UserPwdDo record);
}